global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "type"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: unity-webhook

receivers:
  - name: unity-webhook
    webhook_configs:
      - url: "http://unity-grantmanager-web:80/api/monitoring/alert"
        send_resolved: false
