global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: unity-grantmanager
    static_configs:
      - targets: ["unity-grantmanager-web:8080"]
    metrics_path: /metrics
