apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: add-issue
spec:
  workspaces:
  - name: source
  - name: owasp-settings
    optional: true
    mountPath: /zap/wrk
  params:
  - name: title
    type: string
    description: Issue Title
  - name: body
    type: string
    default: ''
    description: The body of the Issue - Zap Scan Result
  - name: github-secret
    type: string
    default: 'github'
    description: "The name of the secret that has your github username and token"
  steps:
    - name: run-commands
      image: docker.io/michaelin/github-cli:latest
      script: |
        #!/usr/bin/env bash
        # git login
        #echo "GH CLI Auth"
        #echo $(params.github-secret)
        #echo $SECRET > token.txt
        #gh auth login --with-token < token.txt
        #rm token.txt
        # git create issue
        echo "GH Creat issue"
        #echo $GITHUB_USER
        #echo $GITHUB_EMAIL
        #gh issue create -t "$(params.title)" -b "$(params.body)"
        result=$(< /zap/wrk/owasp-quick-results.md)
        echo "echo"
        echo "$result"
        gh issue create -t "Tekton Zap Scan Result" -b "$result"
      workingDir: $(workspaces.source.path)
      env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: github-token
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: password
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: username
        - name: GITHUB_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: email
