# This Task will do a helm upgrade based on the given helm repo and chart
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-deploy
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/categories: Deployment
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: helm
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    These tasks will install / upgrade a helm chart into your Kubernetes /
    OpenShift Cluster using Helm
  workspaces:
    - name: source
  params:
    - name: HELM_DIR
      description: The directory where the helm chart is located.
    - name: HELM_VALUES
      description: The values file relative to helmDir.
    - name: HELM_RELEASE
      description: The release name that will be used to identify the deployment.
    - name: IMAGE
      description: Name of App that will be deployed.
    - name: IMAGE_TAG
      description: Name of image tag.
    - name: HELM_IMAGE
      description: "Specify a specific helm image"
      default: "docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae" #tag: v3.6.0
  steps:
    - name: helm-deploy
      workingDir: $(workspaces.source.path)
      image: $(params.HELM_IMAGE)
      script: |
        helm upgrade --install $(params.HELM_RELEASE) --set image.tag=$(params.IMAGE_TAG) -f $(params.HELM_DIR)/$(params.HELM_VALUES) $(params.HELM_DIR)
