version: '3.4'

services:
  unity.workflows:
    image: ${DOCKER_REGISTRY-}unity
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5095:5095"
    depends_on:
      unity-portal-orchestrator-db:
        condition: service_healthy
  unity-portal-orchestrator-db:    
    image: postgres:10.5
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    
