apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-database
  namespace: d18498-dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: unity-database
  template:
    metadata:
      labels:
        app: unity-database
    spec:
      containers:
      - name: unity-database
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
        image: mcr.microsoft.com/mssql/rhel/server:2019-CU1-rhel-8
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 1433
          protocol: TCP
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unity-database
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: unity-data
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi   
      volumes:
      - name: unity-data
        persistentVolumeClaim:
          claimName: unity-data