
# Add a resource secret for the database password.
apiVersion: v1
kind: Secret
metadata:
  name: unity-database
  namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
  annotations:
    description: "Database passwords"
  labels:
    name: unity-database
    app: unity
    role: database
    env: dev
type: Opaque
stringData:
    MSSQL_SA_PASSWORD: <Passwd>
    DBUSER_PASSWORD: <Passwd>
