apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following service(s) have been created in your project: ${DATABASE_SERVICE_NAME}.

         Username: ${POSTGRESQL_USER}
         Password: ${POSTGRESQL_PASSWORD}
    Database Name: ${POSTGRESQL_DATABASE}
   Connection URL: unity-database://${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/

  For more information about using this template, including OpenShift considerations, see template 
  usage guide found in the project readme.md and wiki documents.
metadata:
  name: unity-database
  # This template uses a separate parameter .env file to override the default values defined in this section. 
  # oc process -f .\database\unity-database.yaml --param-file=.env | oc create -f -
  labels:
    template: unity-database
  annotations:
    description: |-
      PostgreSQL database service, with persistent storage.
      NOTE: Scaling to more than one replica is not supported. 
    iconClass: icon-postgresql
    openshift.io/display-name: PostgreSQL
    openshift.io/documentation-url: https://docs.okd.io/latest/using_images/db_images/postgresql.html
    openshift.io/long-description: This template provides a standalone PostgreSQL
      server with an initial database created.  The database is stored on persistent storage.
      The database name, username, and password are chosen via parameters when provisioning.
    tags: database,postgresql
parameters:
# Project namespace parameters
- description: The name of the application grouping.
  displayName: Application Group
  name: APPLICATION_GROUP
  required: true
  value: unity-grantmanager
- description: The name of the backup application.
  displayName: Application Name
  name: BACKUP_APPLICATION_NAME
  required: true
  value: unity-backup
# Additional parameters for project database provisioning
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: unity-data-postgres
- description: The port exposed for the database.
  displayName: Database Service Port
  name: DATABASE_PORT
  required: true
  value: "5432"
- description: Username for PostgreSQL user that will be used for accessing the database.
  displayName: PostgreSQL Connection Username
  name: POSTGRESQL_USER
  required: true
  value: "postgres"
- description: Password for the PostgreSQL connection user.
  displayName: PostgreSQL Connection Password
  name: POSTGRESQL_PASSWORD
  required: true
  from: '[a-zA-Z0-9]{26}'
  generate: expression
- description: Name of the PostgreSQL database accessed.
  displayName: PostgreSQL Database Name
  name: POSTGRESQL_DATABASE
  required: true
  value: UnityGrantManager
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 256Mi
- description: The Namespace where the database container image resides default=redhat cluster=openshift, project=tools
  displayName: Registry Namespace
  name: IMAGEPULL_NAMESPACE
  required: true
  value: redhat
- description: The Openshift ImageStream Name
  displayName: Registry imagestream name
  name: IMAGESTREAM_NAME
  required: true
  value: postgresql-15  
- description: The version of the postgresql container image to use.
  displayName: Registry container image  to pull
  name: IMAGESTREAM_TAG
  required: true
  value: latest
- description: The registry path of the postgresql container image to use.
  displayName: Registry container image to pull
  name: IMAGEPULL_REGISTRY
  required: true
  value: registry.redhat.io/rhel9/
# Resource limits control how much CPU and memory a container will consume
- description: The minimum amount of CPU the Container is guaranteed.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 50m
- description: The maximum amount of CPU the Container is allowed to use when running.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 250m
- description: The minimum amount of Memory the Container is guaranteed.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: The maximum amount of Memory the Container is allowed to use when running.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
# Template objects to instantiate the project database.
objects:
# Secrets 
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: ${DATABASE_SERVICE_NAME}
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}    
  stringData:
    database-name: ${POSTGRESQL_DATABASE}
    database-password: ${POSTGRESQL_PASSWORD}
    database-user: ${POSTGRESQL_USER}
  type: Opaque
# Configmap
- apiVersion: v1 
  kind: ConfigMap 
  metadata:
    name: ${DATABASE_SERVICE_NAME}
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  data:
    # Configuration values can be set as key-value properties
    UNITY_DB_PORT: ${DATABASE_PORT}
# Service
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    name: ${DATABASE_SERVICE_NAME}
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}    
  spec:
    ports:
    - name: ${DATABASE_SERVICE_NAME}
      nodePort: 0
      protocol: TCP
      port: ${{DATABASE_PORT}}
      targetPort: ${{DATABASE_PORT}}
    selector:
      name: ${DATABASE_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# Persistent storage for the database.
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DATABASE_SERVICE_NAME}
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
      storageClassName: netapp-file-standard
      volumeMode: Filesystem
# Persistent storage for the database backups.
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: unity-data-backup
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
      storageClassName: netapp-file-standard
      volumeMode: Filesystem
# Deployment Config
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${DATABASE_SERVICE_NAME}
    labels:
      app: ${DATABASE_SERVICE_NAME}
      app.openshift.io/runtime: postgresql
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${DATABASE_SERVICE_NAME}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${DATABASE_SERVICE_NAME}
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${DATABASE_SERVICE_NAME}
          - name: PGPORT
            value: ${DATABASE_PORT}
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: postgresql
          ports:
          - containerPort: ${{DATABASE_PORT}}
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: ${DATABASE_SERVICE_NAME}-data
          - mountPath: /var/lib/pgsql/backups
            name: unity-data-backups
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ${DATABASE_SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: ${DATABASE_SERVICE_NAME}
        - name: unity-data-backups
          persistentVolumeClaim:
            claimName: unity-data-backup
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: ${IMAGESTREAM_NAME}:${IMAGESTREAM_TAG}
          namespace: ${IMAGEPULL_NAMESPACE}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
