apiVersion: template.openshift.io/v1
kind: Template
message: |-
  A scheduled cronjob has been created in your project: unity-backup.
  For more information about using this template, including OpenShift considerations, 
  see template usage guide found in the project readme.md and wiki documents.
metadata:
  name: unity-backup-cronjob
  # This template uses a separate parameter .env file to override the default values defined in this section. 
  # oc process -f .\openshift\unity-backup-cronjob.yaml | oc create -f -
  labels:
    template: unity-backup-cronjob  
  annotations:
    description: |-
      Template for running a recurring backup script in OpenShift.
    iconClass: icon-build
    openshift.io/display-name: Database Backup Cronjob
    template.openshift.io/long-description: |-
      This template defines resources needed to build and deploy a postgresql container application.
    tags: unity-database,postgresql
parameters:
# Project namespace parameters
- description: The name of the backup application.
  displayName: Application Name
  name: BACKUP_APPLICATION_NAME
  required: true
  value: unity-backup
- description: The name of the application grouping.
  displayName: Application Group
  name: APPLICATION_GROUP
  value: Triggers
# Additional parameters for project application provisioning.
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: unity-data-postgres
- description: The port exposed for the database.
  displayName: Database Service Port
  name: DATABASE_PORT
  required: true
  value: "5432"
- description: Password for the PostgreSQL connection user.
  displayName: PostgreSQL Connection Password
  name: POSTGRESQL_PASSWORD
  from: '[a-zA-Z0-9]{26}'
  generate: expression
- name: DATABASE_BACKUP_KEEP
  description: 'Number of backups to keep'
  value: '28'
- name: DATABASE_BACKUP_SCHEDULE
  description: 'Cron-like schedule expression m h D M DayOfWeek add +7/8 hours for UTC conversions'
  value: '0 0,14 * * *'
- name: DATABASE_BACKUP_VOLUME_CLAIM
  description: 'Name of the volume claim to be used as storage'
  required: true
  value: unity-data-backup
- description: The Namespace where the database container image resides default=redhat cluster=openshift, project=tools
  displayName: Registry Namespace
  name: IMAGEPULL_NAMESPACE
  value: redhat
- description: The Openshift ImageStreams Name
  displayName: Registry imagestream name
  name: IMAGESTREAM_NAME
  value: postgresql-15  
- description: The version of the postgresql container image to use.
  displayName: Registry container image  to pull
  name: IMAGESTREAM_TAG
  required: true
  value: latest
- description: The registry path of the postgresql container image to use.
  displayName: Registry container image to pull
  name: IMAGEPULL_REGISTRY
  value: registry.redhat.io/rhel9/
# Template objects to instantiate the project.
objects:
# Recurring cronjob for Database Backups
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: ${BACKUP_APPLICATION_NAME}
    labels:
      job-name: ${BACKUP_APPLICATION_NAME}
      app.kubernetes.io/component: ${DATABASE_SERVICE_NAME}
      app.kubernetes.io/instance: ${DATABASE_SERVICE_NAME}-1
      app.kubernetes.io/name: ${BACKUP_APPLICATION_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  # Cronjob script works with both database or instance backup commands
  # pg_dump --username=$DATABASE_USER --host=$DATABASE_HOST --port=$DATABASE_PORT --column-inserts --clean --create ${DATABASE_SERVICE_NAME} 
  # pg_dumpall --username=$DATABASE_USER --host=$DATABASE_HOST --port=$DATABASE_PORT --column-inserts --clean
  spec:
    schedule: ${DATABASE_BACKUP_SCHEDULE}
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          spec:
            volumes:
              - name: ${BACKUP_APPLICATION_NAME}
                persistentVolumeClaim:
                  claimName: ${DATABASE_BACKUP_VOLUME_CLAIM}
            containers:
              - name: ${BACKUP_APPLICATION_NAME}
                image: ${IMAGEPULL_REGISTRY}/${IMAGEPULL_NAMESPACE}/${IMAGESTREAM_NAME}:${IMAGESTREAM_TAG}
                command:
                  - 'bash'
                  - '-eo'
                  - 'pipefail'
                  - '-c'
                  - > 
                    trap "echo Backup failed; exit 0" ERR; date;
                    FILENAME=dumpall-${DATABASE_SERVICE_NAME}-`date +%Y-%m-%d_%H%M%S`.sql.gz;
                    time (find /var/lib/pgsql/backups -type f -name "*-${DATABASE_SERVICE_NAME}-*"  -exec ls -1tr "{}" + | head -n -${DATABASE_BACKUP_KEEP} | xargs rm -fr; 
                    PGPASSWORD="$DATABASE_PASSWORD" pg_dumpall --username=$DATABASE_USER --host=$DATABASE_HOST --port=$DATABASE_PORT --column-inserts --clean | gzip > /var/lib/pgsql/backups/$FILENAME); 
                    echo "";
                    echo "Backup successful"; du -h /var/lib/pgsql/backups/$FILENAME; 
                    echo "to restore the backup to the serviced host use: $ psql --username=$DATABASE_USER --password --host=$DATABASE_HOST --port=$DATABASE_PORT postgres < /var/lib/pgsql/backups/<backupfile> (unpacked with gunzip)";
                    echo ""; du -hc /var/lib/pgsql/backups/*
                env:
                  - name: DATABASE_PORT
                    valueFrom:
                      configMapKeyRef:
                        name: ${DATABASE_SERVICE_NAME}
                        key: UNITY_DB_PORT
                  - name: DATABASE_HOST
                    value: ${DATABASE_SERVICE_NAME}
                  - name: DATABASE_SERVICE_NAME
                    valueFrom:
                      secretKeyRef:
                        name: ${DATABASE_SERVICE_NAME}
                        key: database-name
                  - name: DATABASE_USER
                    valueFrom:
                      secretKeyRef:
                        name: ${DATABASE_SERVICE_NAME}
                        key: database-user
                  - name: DATABASE_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: ${DATABASE_SERVICE_NAME}
                        key: database-password
                  - name: DATABASE_BACKUP_KEEP
                    value: ${DATABASE_BACKUP_KEEP}
                  - name: TZ
                    value: Canada/Pacific
                volumeMounts:
                  - name: ${BACKUP_APPLICATION_NAME}
                    mountPath: /var/lib/pgsql/backups
            restartPolicy: Never
