# Persistent storage for the database.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
      name: unity-data
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: unity-data
        app: unity
        env: dev
        role: database
spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 250Mi
      storageClassName: netapp-file-standard
      volumeMode: Filesystem
---
# Persistent storage for the database backups.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
      name: unity-backup
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: unity-backup
        app: unity
        env: dev
        role: backup
spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 250Mi
      storageClassName: netapp-file-standard
      volumeMode: Filesystem