apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-build-deploy
spec:
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  params:
    - name: helmDir
      type: string
      description: The directory where the helm chart is located.
    - name: helmValues
      type: string
      description: The values file relative to helmDir.
    - name: helmRelease
      type: string
      description: The release name that will be used to identify the deployment.
    - name: helmImage
      type: string
      description: The helm docker image url to use.
    - name: imageRegistry
      type: string
      description: The Root url of the image registry. (ie. docker.io)
    - name: imageRegistryUser
      type: string
      description: The secret name of the secret holding the username.
    - name: imageRegistryPass
      type: string
      description: The secret name of the secret holding the password.
    - name: imageUrl
      type: string
    - name: repoUrl
      type: string
      description: The git repository URL to clone from.
    - name: branchName
      type: string
      description: The git branch to clone.
    - name: pathToContext
      type: string
      description: Path of the Dockerfile.
    - name: dockerfile
      type: string
      description: Location of the Dockerfile.
    - name: buildahImage
      type: string
      description: Version of Buildah to run.
  tasks:
    - name: fetch-repository
      taskRef:
        name: t-git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repoUrl)
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.branchName)
    - name: generate-id
      taskRef:
        name: t-generate-id
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
    - name: buildah-build-push
      taskRef:
        name: t-buildah
      runAfter:
        - generate-id
      params:
        - name: IMAGE
          value: $(params.imageUrl)
        - name: IMAGE_TAG
          value: $(tasks.generate-id.results.short-commit)
        - name: IMAGE_REGISTRY
          value: $(params.imageRegistry)
        - name: IMAGE_REGISTRY_USER
          value: $(params.imageRegistryUser)
        - name: IMAGE_REGISTRY_PASS
          value: $(params.imageRegistryPass)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: BUILDAH_IMAGE
          value: $(params.buildahImage)
      workspaces:
        - name: source
          workspace: shared-data
    - name: helm-deploy
      taskRef:
        name: t-helm-deploy
      runAfter:
        - buildah-build-push
      params:
        - name: HELM_DIR
          value: $(params.helmDir)
        - name: HELM_VALUES
          value: $(params.helmValues)
        - name: HELM_RELEASE
          value: $(params.helmRelease)
        - name: HELM_IMAGE
          value: $(params.helmImage)
        - name: IMAGE
          value: $(params.imageUrl)
        - name: IMAGE_TAG
          value: $(tasks.generate-id.results.short-commit)
      workspaces:
        - name: source
          workspace: shared-data
