apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: trivy
spec:
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  params:
  - name: targetImage
    type: string
    description: The URL of the image to be Scanned.
  - name: imageRegistryUser
    type: string
    description: The secret name of the secret holding the username.
  - name: imageRegistryPass
    type: string
    description: The secret name of the secret holding the password.
  tasks:
    - name: trivy-scan
      taskRef:
        name: t-trivy-scanner
      params:
        - name: TARGET_IMAGE
          value: $(params.targetImage)
        - name: IMAGE_REGISTRY_USER
          value: $(params.imageRegistryUser)
        - name: IMAGE_REGISTRY_PASS
          value: $(params.imageRegistryPass)
      workspaces:
        - name: source
          workspace: shared-data
