apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tekon-triggers
resources:
  - ingress.yaml
  # switch to use the default serviceAccount/pipeline
  # - rbac.yaml
  - trigger-flask-web.yaml
  - trigger-maven-build.yaml
