apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-image-trigger
spec:
  params:
  - name: appName
    default: flask-web
  - name: repoUrl
    default: https://github.com/bcgov/pipeline-templates.git
  - name: imageUrl
    default: gregnrobinson/tkn-flask-web:latest
  - name: branchName
    default: main
  - name: dockerfile
    default: ./Dockerfile
  - name: pathToContext
    default: ./tekton/demo/flask-web
  - name: buildahImage
    default: quay.io/buildah/stable:v1.23.1
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: docker-build-push-run-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: p-buildah
      params:
      - name: appName
        value: $(tt.params.appName)
      - name: repoUrl
        value: $(tt.params.repoUrl)
      - name: imageUrl
        value: $(tt.params.imageUrl)
      - name: branchName
        value: $(tt.params.branchName)
      - name: dockerfile
        value: $(tt.params.dockerfile)
      - name: pathToContext
        value: $(tt.params.pathToContext)
      - name: buildahImage
        value: $(tt.params.buildahImage)
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi
      - name: docker-config
        secret:
          secretName: docker-config-path
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-push-image-trigger
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: github-webhook-secret
            eventTypes:
              - pull_request
              - push
      bindings:
        - ref: pipeline-templates
      template:
        ref: build-push-image-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-templates
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
