apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: maven-build-trigger
spec:
  params:
  - name: appName
    default: maven-test
  - name: mavenImage
    default: index.docker.io/library/maven
  - name: repoUrl
    default: https://github.com/bcgov/pipeline-templates.git
  - name: branchName
    default: main
  - name: pathToContext
    default: ./tekton/demo/maven-test
  - name: runSonarScan
    default: 'true'
  - name: sonarProject
    default: bcgov_pipeline-templates
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: maven-build-run-
    spec:
      pipelineRef:
        name: p-mvn-build
      params:
      - name: appName
        value: $(tt.params.appName)
      - name: mavenImage
        value: $(tt.params.mavenImage)
      - name: repoUrl
        value: $(tt.params.repoUrl)
      - name: branchName
        value: $(tt.params.branchName)
      - name: pathToContext
        value: $(tt.params.pathToContext)
      - name: runSonarScan
        value: $(tt.params.runSonarScan)
      - name: sonarProject
        value: $(tt.params.sonarProject)
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: docker-config
        secret:
          secretName: docker-config-path
      - name: maven-settings
        emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: maven-build-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
              - push
      bindings:
        - ref: maven-build-trigger-binding
      template:
        ref: maven-build-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: maven-build-trigger-binding
spec:
  params:
  - name: branchName
    value: $(body.ref)
  - name: repoUrl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
