{{- if and .Values.dataRestore.enabled .Values.dataRestore.createS3Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataRestore.secretName | default "dev-s3-restore" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crunchy-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Same format as pgBackRest secret - using s3.conf key name to match
  s3.conf: |
    [global]
    repo2-s3-key={{ .Values.dataRestore.s3.key }}
    repo2-s3-key-secret={{ .Values.dataRestore.s3.keySecret }}
{{- end }}
