apiVersion: template.openshift.io/v1
kind: Template
message: |-
  A pipeline has been created in your project: unity-release.
  For more information about using this template, including OpenShift considerations, 
  see template usage guide found in the project readme.md and wiki documents.
metadata:
  name: unity-release-pipeline
  # This template uses a separate parameter .env file to override the default values defined in this section. 
  # oc process -f .\openshift\unity-release-pipeline.yaml --param-file=.env | oc create -f -
  labels:
    template: unity-release-pipeline
  annotations:
    description: |-
      Template for running an application build and deployment in OpenShift.
    iconClass: icon-build
    openshift.io/display-name: DotNet console application
    template.openshift.io/long-description: |-
      This template defines resources needed to build and deploy a GitHub DotNet core console application.
    tags: dotnet,unity-release
parameters:
# Project namespace parameters
- description: The name of the application grouping.
  displayName: Application Group
  name: APPLICATION_GROUP
  value: unity-grantmanager
- description: The name of the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: unity-grantmanager-web
# Template objects to instantiate the project.
objects:
# Pipeline for Database Migrator
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: unity-release
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}-1
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
  spec:
    tasks:
      - name: describe-templates
        params:
          - name: SCRIPT
            value: oc describe templates
          - name: VERSION
            value: latest
        taskRef:
          kind: ClusterTask
          name: openshift-client
      - name: clean-dbmigrator-jobs
        params:
          - name: SCRIPT
            value: 'oc delete jobs unity-grantmanager-dbmigrator '
          - name: VERSION
            value: latest
        runAfter:
          - start-build-unity-dbmigrator
        taskRef:
          kind: ClusterTask
          name: openshift-client
      - name: run-dbmigrator-job
        params:
          - name: SCRIPT
            value: >-
              oc process unity-grantmanager-dbmigrator-job | oc create -f -
          - name: VERSION
            value: latest
        runAfter:
          - clean-dbmigrator-jobs
          - start-build-unity-dbmigrator
          - start-build-unity-grantmanager-web
        taskRef:
          kind: ClusterTask
          name: openshift-client
      - name: start-build-unity-grantmanager-web
        params:
          - name: SCRIPT
            value: oc start-build unity-grantmanager-web --follow
          - name: VERSION
            value: latest
        runAfter:
          - describe-templates
        taskRef:
          kind: ClusterTask
          name: openshift-client
      - name: start-build-unity-dbmigrator
        params:
          - name: SCRIPT
            value: oc start-build unity-grantmanager-dbmigrator --follow
          - name: VERSION
            value: latest
        runAfter:
          - start-build-unity-grantmanager-web
        taskRef:
          kind: ClusterTask
          name: openshift-client
