apiVersion: template.openshift.io/v1
kind: Template
message: |-
  A job has been created in your project: unity-grantmanager-dbmigrator-job.
  For more information about using this template, including OpenShift considerations, 
  see template usage guide found in the project readme.md and wiki documents.
metadata:
  name: unity-grantmanager-dbmigrator-job
  # This template uses a separate parameter .env file to override the default values defined in this section. 
  # oc process -f .\openshift\unity-grantmanager-dbmigrator-job.yaml --param-file=.env | oc create -f -
  labels:
    template: unity-grantmanager-dbmigrator-job
  annotations:
    description: |-
      Template for running a dotnet console application once in OpenShift.
    iconClass: icon-build
    openshift.io/display-name: Database Migrator Job
    template.openshift.io/long-description: |-
      This template defines resources needed to build and deploy a container application.
    tags: dotnet,unity-grantmanager-dbmigrator
parameters:
# Project namespace parameters
- description: The name of the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: unity-grantmanager-dbmigrator
- description: The name of the application grouping.
  displayName: Application Group
  name: APPLICATION_GROUP
  value: Triggers
# Additional parameters for project application provisioning.
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: unity-data-postgres
- description: Git source URI for application
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: 'https://github.com/bcgov/Unity'
- description: Name of the tenant database accessed.
  displayName: PostgreSQL Tenant Database Name
  name: UNITY_TENANT_DB
  value: UnityGrantTenant 
# Base image location
- description: The Namespace where the container image resides
  displayName: Registry Namespace
  name: IMAGEPULL_NAMESPACE
  from: '[a-zA-Z0-9]{5}-tools'
  generate: expression
- description: The ImageStream Name 
  displayName: Registry imagestream name
  name: IMAGESTREAM_NAME
  value: unity-dbmigrator-build 
- description: The version of the image to use, e.g. v1.0.0, v0.1.0, latest the ImageStream tag.
  displayName: Application Version
  name: IMAGESTREAM_TAG
  required: true
  value: latest
- description: The registry path of the container image used.
  displayName: Registry location to pull from
  name: IMAGEPULL_REGISTRY
  value: image-registry.openshift-image-registry.svc:5000/
# Template objects to instantiate the project.
objects:
# RunOnce Job for Database Migrator
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      job-name: ${APPLICATION_NAME}
      app.openshift.io/runtime: build
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}-1
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_GROUP}
    annotations:
      app.openshift.io/vcs-uri: ${SOURCE_REPOSITORY_URL}
  spec:
    parallelism: 1
    completions: 1
    backoffLimit: 1
    selector: {}
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          application: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            image: ${IMAGEPULL_REGISTRY}${IMAGEPULL_NAMESPACE}/${IMAGESTREAM_NAME}:${IMAGESTREAM_TAG}
            env:
              - name: UNITY_DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: ${DATABASE_SERVICE_NAME}
                    key: UNITY_DB_PORT
              - name: UNITY_DB_HOST
                value: ${DATABASE_SERVICE_NAME}
              - name: UNITY_POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: ${DATABASE_SERVICE_NAME}
                    key: database-name
              - name: UNITY_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: ${DATABASE_SERVICE_NAME}
                    key: database-user
              - name: UNITY_POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${DATABASE_SERVICE_NAME}
                    key: database-password
              - name: UNITY_TENANT_DB
                value: ${UNITY_TENANT_DB}
              - name: ConnectionStrings__Default
                value: >-
                  Host=$(UNITY_DB_HOST);port=$(UNITY_DB_PORT);Database=$(UNITY_POSTGRES_DB);Username=$(UNITY_POSTGRES_USER);Password=$(UNITY_POSTGRES_PASSWORD)
              - name: ConnectionStrings__Tenant
                value: >-
                  Host=$(UNITY_DB_HOST);port=$(UNITY_DB_PORT);Database=$(UNITY_TENANT_DB);Username=$(UNITY_POSTGRES_USER);Password=$(UNITY_POSTGRES_PASSWORD)
        restartPolicy: Never
