apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: unity-networkpolicy
  # This template uses a separate parameter .env file to override the default values defined in this section. 
  # oc process -f .\openshift\unity-network-policy.yaml --param-file=.env | oc create -f -
  labels:
    template: unity-networkpolicy
  annotations:
    description: |-
      Template for communications rules in OpenShift.
parameters:
# Project namespace parameters
- description: The name of the application grouping.
  displayName: Application Group
  name: APPLICATION_GROUP
  value: unity-grantmanager
- description: The name of the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: unity-grantmanager-web
# Template objects to instantiate the project application.
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: deny-by-default
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}-1
        app.kubernetes.io/name: ${APPLICATION_NAME}
        app.kubernetes.io/part-of: ${APPLICATION_GROUP}
    spec:
      # The default posture for a security first namespace is to
      # deny all traffic. If not added this rule will be added
      # by Platform Services during environment cut-over.
      podSelector: {}
      ingress: []
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}-1
        app.kubernetes.io/name: ${APPLICATION_NAME}
        app.kubernetes.io/part-of: ${APPLICATION_GROUP}
    spec:
      # This policy allows any pod with a route & service combination
      # to accept traffic from the OpenShift router pods. This is
      # required for things outside of OpenShift (like the Internet)
      # to reach your pods.
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-same-namespace
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/component: ${APPLICATION_NAME}
        app.kubernetes.io/instance: ${APPLICATION_NAME}-1
        app.kubernetes.io/name: ${APPLICATION_NAME}
        app.kubernetes.io/part-of: ${APPLICATION_GROUP}
    spec:
      # Allow all pods within the current namespace to communicate
      # to one another.
      podSelector:
      ingress:
      - from:
        - podSelector: {}
